version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - cd PLOCLO_cms && npm ci
      - python3 -m pip install semgrep

  pre_build:
    commands:
      - echo "Security Review & Preparation"
      - /home/codebuild/.local/bin/semgrep scan --config auto .
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Building Docker Image..."
      - docker-compose -f PLOCLO_cms/docker-compose.yml build

  post_build:
    commands:
      - echo "Pushing to ECR..."
      - docker-compose -f PLOCLO_cms/docker-compose.yml push
      - echo "Build completed on $(date)"
      - printf '[{"name":"backend","imageUri":"%s"},{"name":"frontend","imageUri":"%s"}]' \
        "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:backend-latest" \
        "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:frontend-latest" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json